name: E2E Tests

on:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '00 1 * * *'
  workflow_dispatch:

jobs:

  Ubuntu_Chrome_Grid:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Native Selenium Grid
        run: docker compose -f src/main/resources/docker/docker-compose-v3.yml up -d
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.5
      - name: Check running containers
        run: docker ps
      - name: Run tests
        continue-on-error: true
        run: mvn clean test
          # Build Allure Report
      - name: Build Allure Report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
         gh_pages: master-history
         allure_history: allure-history
         allure_results: target/allure-results  # Adjust this path if necessary

      # Publish Allure Report to the master branch
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_branch: master
           publish_dir: allure-history

          # Upload Allure Report as Pipeline Artifact (Optional if you also want to store it as an artifact)
      - name: Upload Allure Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
           name: Ubuntu_Chrome_Grid_Allure
           path: "target/allure-results/*.html"  # Ensure this matches where the report is generated

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "target/surefire-reports/junitreports/TEST-*.xml"
        if: always()
