name: E2E Tests
'on':
  pull_request:
    branches:
      - master
  schedule:
    - cron: 00 1 * * *
  workflow_dispatch: null
jobs:
  Ubuntu_Chrome_Grid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Native Selenium Grid
        run: docker compose -f src/main/resources/docker/docker-compose-v3.yml up -d
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: zulu
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.5
      - name: Check running containers
        run: docker ps
      - name: Run tests
        continue-on-error: true
        run: mvn clean test
      - name: Build Allure Report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: master-history
          allure_history: allure-history
          allure_results: target/allure-results
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          publish_branch: master
          publish_dir: allure-history
      - name: Upload Allure Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Ubuntu_Chrome_Grid_Allure
          path: target/allure-results/*.html
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: target/surefire-reports/junitreports/TEST-*.xml
        if: always()
