name: E2E Tests
on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '00 1 * * *'
  workflow_dispatch:

jobs:
  Ubuntu_Chrome_Grid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Native Selenium Grid
        run: docker compose -f src/main/resources/docker/docker-compose-v3.yml up -d

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: zulu
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.5

      - name: Check running containers
        run: docker ps

      - name: Run tests
        continue-on-error: true
        run: mvn clean test -Dbrowser=chrome -Dallure.results.directory=target/allure-results/chrome

      - name: Verify Test Results
        run: |
          ls -R target/allure-results/chrome
      

      - name: Generate Allure Report using Docker
        run: |
          docker run --rm -u $(id -u):$(id -g) -v ${{ github.workspace }}:/allure -w /allure frankescobar/allure-docker-service:latest allure generate --clean target/allure-results/chrome -o target/allure-results/chrome

      - name: Upload Allure Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Ubuntu_Chrome_Grid_Allure
          path: target/allure-results/chrome

      - name: Upload Extend Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Ubuntu_Chrome_Grid_Extend_Report
          path: target/extend-report

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: target/surefire-reports/junitreports/TEST-*.xml
        if: always()

