name: E2E Tests
'on':
  pull_request:
    branches:
      - master
  schedule:
    - cron: 00 1 * * *
  workflow_dispatch: null
jobs:
  Ubuntu_Chrome_Grid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Native Selenium Grid
        run: docker compose -f src/main/resources/docker/docker-compose-v3.yml up -d
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: zulu
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.5
      - name: Check running containers
        run: docker ps
      - name: Run tests
        continue-on-error: true
        run: mvn clean test

      - name: Get Allure history # Step to retrieve Allure history
        uses: actions/checkout@v3
        if: always() # Execute even if previous steps fail
        continue-on-error: true # Continue execution even if the step fails
        with:
          ref: gh-pages # Specify the branch to retrieve Allure history from
          path: gh-pages # Set the destination path for Allure history

      - name: Generate Allure report  # Step to generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always() # Execute even if previous steps fail
        with:
          allure_results: target/allure-results # Specify the directory containing Allure results
          allure_history: allure-history # Specify the directory to store Allure history
          keep_reports: 5 # Specify the number of previous reports to keep

      - name: Upload Allure Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Ubuntu_Chrome_Grid_Allure
          path: /allure-history/last-history/*.html

      - name: Upload Extend Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Ubuntu_Chrome_Grid_Allure
          path: target/extend-results/*.html

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: target/surefire-reports/junitreports/TEST-*.xml
        if: always()
